# Generated by Django 5.0.4 on 2024-06-07 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='check.lesson')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.examtime')),
            ],
        ),
    ]
